name: Gradle Package

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'gradle'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build

      - name: Upload build artifacts api
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: api/build/libs

      - name: Upload build artifacts spigot
        uses: actions/upload-artifact@v4
        with:
          name: spigot-build
          path: spigot/build/libs

      - name: Upload build artifacts netty-common
        uses: actions/upload-artifact@v4
        with:
          name: netty-common-build
          path: netty-common/build/libs

      - name: Upload build artifacts bungeecord
        uses: actions/upload-artifact@v4
        with:
          name: bungeecord-build
          path: bungeecord/build/libs

      - name: Upload build artifacts velocity
        uses: actions/upload-artifact@v4
        with:
          name: velocity-build
          path: velocity/build/libs

      - name: Upload build artifacts fabric
        uses: actions/upload-artifact@v4
        with:
          name: fabric-build
          path: fabric/build/libs

  extract-javadoc:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    needs:
      - build

    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Extract Javadoc Jars
        run: |
          ls | xargs -L 1 | awk '/.+-javadoc\.jar/{print $0}' | awk 'BEGIN{FS=OFS="-"}{NF-=3; print}' | awk '!NF || !seen[$0]++' | awk '{cmd="mkdir "$0" && unzip -d ./"$0"/ "$0"-*-javadoc.jar"; print cmd}' | tr '\n' ';' | sh && rm *'.jar'

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy-javadoc:
    needs: extract-javadoc

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
